export const itemConstants = {
  ADD_SUCCESS: "ADD_SUCCESS",
  ADD_FAILURE: "ADD_FAILURE",
  GET_ALL_REQUEST: "ITEMS_GET_ALL_REQUEST",
  GET_ALL_SUCCESS: "ITEMS_GET_ALL_SUCCESS",
  GET_ALL_FAILURE: "ITEMS_GET_ALL_FAILURE",
  DELETE_REQUEST: "ITEMS_DELETE_REQUEST",
  DELETE_SUCCESS: "ITEMS_DELETE_SUCCESS",
  DELETE_FAILURE: "ITEMS_DELETE_FAILURE"
};
